### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by tigerofmurder** [njoosse/cpp-compiler#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [cpp-compiler](https://github.com/njoosse/cpp-compiler) package 0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At C:\Users\jonathan\.atom\packages\cpp-compiler\lib\cpp-compiler.js:53

TypeError: Cannot read property 'path' of null
    at getFilePath (/packages/cpp-compiler/lib/cpp-compiler.js:52:6)
    at compileAndRun (/packages/cpp-compiler/lib/cpp-compiler.js:21:18)
    at /packages/cpp-compiler/lib/cpp-compiler.js:73:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  4x -3:26.7.0 core:backspace (input.hidden-input)
     -3:05.2.0 cpp-compiler:compile (input.hidden-input)
     -2:16.1.0 cpp-compiler:compileAndRun (div.line.cursor-line)
     -1:57.2.0 core:backspace (input.hidden-input)
  2x -1:54.3.0 core:move-down (input.hidden-input)
     -1:52.9.0 autocomplete-plus:confirm (input.hidden-input)
     -1:50 editor:newline (input.hidden-input)
  5x -1:41.2.0 core:backspace (input.hidden-input)
     -1:32.4.0 editor:newline (input.hidden-input)
     -1:20.9.0 core:backspace (input.hidden-input)
     -1:19.7.0 editor:newline (input.hidden-input)
     -1:02.3.0 snippets:next-tab-stop (input.hidden-input)
     -1:02.3.0 snippets:expand (input.hidden-input)
     -1:02.3.0 editor:indent (input.hidden-input)
  3x -1:00.1.0 core:backspace (input.hidden-input)
     -0:44.5.0 cpp-compiler:compileAndRun (div.lines)
```

### Non-Core Packages

```
cpp-compiler 0.1.0 
pythoncompiler 2.0.0 
```

**Comment by njoosse** [comment]
Hello,
Thank you for opening an issue report.
Are you attempting the Compile and Run on an unsaved file?
